plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.ksp)
    alias(libs.plugins.hilt)
}

android {
    namespace = "com.example.oms.feature.email"
    compileSdk = libs.versions.compile.sdk.get().toInteger()

    defaultConfig {
        minSdk = libs.versions.min.sdk.get().toInteger()
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation project(":core")

    implementation libs.hilt.android
    ksp libs.hilt.compiler
}
