plugins {
    alias(libs.plugins.android.library)
}

android {
    namespace = "com.example.oms.core"
    compileSdk = libs.versions.compile.sdk.get().toInteger()

    defaultConfig {
        minSdk = libs.versions.min.sdk.get().toInteger()
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation libs.coroutines.core
}
