plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.ksp)
    alias(libs.plugins.hilt)
}

android {
    namespace = "com.example.oms"
    compileSdk = libs.versions.compile.sdk.get().toInteger()

    defaultConfig {
        applicationId = "com.example.oms"
        minSdk = libs.versions.min.sdk.get().toInteger()
        targetSdk = libs.versions.target.sdk.get().toInteger()
        versionCode = 1
        versionName = "1.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    buildFeatures {
        compose = true
    }

    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }
}

dependencies {
    implementation project(":core")
    implementation project(":feature:camera")
    implementation project(":feature:template")
    implementation project(":feature:email")
    implementation project(":data:local")
    implementation project(":data:remote")

    implementation platform(libs.compose.bom)
    implementation libs.compose.ui
    implementation libs.compose.ui.tooling.preview
    implementation libs.compose.material3
    implementation libs.activity.compose
    implementation libs.activity.ktx
    implementation libs.lifecycle.runtime.ktx
    implementation libs.navigation.compose
    implementation libs.coroutines.android
    implementation libs.coroutines.core

    implementation libs.hilt.android
    ksp libs.hilt.compiler
    implementation libs.hilt.navigation.compose

    testImplementation libs.junit
    androidTestImplementation libs.androidx.test.ext.junit
    androidTestImplementation libs.espresso.core
    androidTestImplementation platform(libs.compose.bom)
    androidTestImplementation libs.compose.ui.test.junit4
    debugImplementation libs.compose.ui.tooling
    debugImplementation libs.compose.ui.test.manifest
}
